import Header from "@/components/admin/Header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./index.css";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <Header />
          {children}
          <Toaster />
        </main>
      </body>
    </html>
  );
}
